####
FROM node:22-alpine3.18

RUN mkdir -p /var/www/app

WORKDIR /var/www/app

RUN apk update && apk upgrade

COPY package.json .

COPY package-lock.json .

RUN npm install

# Copy existing application directory contents
COPY . .

EXPOSE 3000

CMD [ "npm", "run", "start" ]
